"""
field.urdf を解析して占有格子地図 (Occupancy Grid) を生成するモジュール。

URDF 内のすべての box 型 collision ジオメトリを障害物として扱い、
指定した解像度のグリッドにラスタライズする。

使い方:
    python occupancy_grid.py          # 直接実行 → occupancy_grid.npy を上書き保存
    import occupancy_grid             # 他モジュールから関数として利用
"""

import os
import xml.etree.ElementTree as ET

import numpy as np


def generate_occupancy_grid_from_urdf(
    urdf_path: str,
    resolution: float = 0.01,
    output_path: str | None = None,
) -> tuple[np.ndarray, dict]:
    """
    field.urdf を解析して占有格子地図を生成する。

    Parameters
    ----------
    urdf_path : str
        field.urdf のパス。
    resolution : float
        1 セルの実寸 [m]。デフォルト 0.01 m = 1 cm。
    output_path : str | None
        指定した場合、グリッドを .npy 形式で保存する。

    Returns
    -------
    grid : np.ndarray, shape (H, W), dtype=uint8
        0 = 空き領域、1 = 障害物セル。
    info : dict
        {
            "resolution" : float,        # m/cell
            "origin"     : (x_min, y_min), # グリッド左下の世界座標 [m]
            "width"      : int,           # X 方向セル数
            "height"     : int,           # Y 方向セル数
        }
    """
    tree = ET.parse(urdf_path)
    root = tree.getroot()

    # ── リンク名 → box XY サイズの辞書を構築 ──────────────────────────────
    link_sizes: dict[str, tuple[float, float]] = {}
    for link in root.findall("link"):
        name = link.get("name")
        # collision > geometry > box を優先、なければ visual から取得
        box = link.find(".//collision/geometry/box")
        if box is None:
            box = link.find(".//visual/geometry/box")
        if box is not None:
            parts = box.get("size", "0 0 0").split()
            sx, sy = float(parts[0]), float(parts[1])
            # base_point などのダミーリンク (サイズが tiny) は除外
            if sx > 1e-3 and sy > 1e-3:
                link_sizes[name] = (sx, sy)

    # ── ジョイントから各リンクの世界座標を収集 ────────────────────────────
    # base_point が原点 (0, 0) として扱われる
    # すべての child は base_point からの固定オフセットで定義されている
    obstacles: list[tuple[float, float, float, float]] = []  # (cx, cy, sx, sy)

    for joint in root.findall("joint"):
        child_el  = joint.find("child")
        origin_el = joint.find("origin")
        if child_el is None or origin_el is None:
            continue
        child_name = child_el.get("link")
        if child_name not in link_sizes:
            continue
        xyz = origin_el.get("xyz", "0 0 0").split()
        cx, cy = float(xyz[0]), float(xyz[1])
        sx, sy = link_sizes[child_name]
        obstacles.append((cx, cy, sx, sy))

    if not obstacles:
        raise ValueError("URDF から障害物となる box リンクを検出できませんでした。")

    # ── フィールド範囲を計算 ──────────────────────────────────────────────
    x_min = min(cx - sx / 2 for cx, cy, sx, sy in obstacles)
    x_max = max(cx + sx / 2 for cx, cy, sx, sy in obstacles)
    y_min = min(cy - sy / 2 for cx, cy, sx, sy in obstacles)
    y_max = max(cy + sy / 2 for cx, cy, sx, sy in obstacles)

    # 境界に余白を追加
    margin = resolution * 5
    x_min -= margin
    x_max += margin
    y_min -= margin
    y_max += margin

    width  = int(np.ceil((x_max - x_min) / resolution))
    height = int(np.ceil((y_max - y_min) / resolution))

    grid = np.zeros((height, width), dtype=np.uint8)

    def _world_to_cell(x: float, y: float) -> tuple[int, int]:
        """世界座標 → グリッドインデックス (row, col) へ変換。"""
        col = int((x - x_min) / resolution)
        row = int((y - y_min) / resolution)
        return row, col

    # ── 各障害物をグリッドへラスタライズ ─────────────────────────────────
    for cx, cy, sx, sy in obstacles:
        r0, c0 = _world_to_cell(cx - sx / 2, cy - sy / 2)
        r1, c1 = _world_to_cell(cx + sx / 2, cy + sy / 2)
        # グリッド境界でクリップ
        r0 = max(0, min(r0, height - 1))
        r1 = max(0, min(r1 + 1, height))
        c0 = max(0, min(c0, width  - 1))
        c1 = max(0, min(c1 + 1, width))
        grid[r0:r1, c0:c1] = 1

    info: dict = {
        "resolution": resolution,
        "origin"    : (x_min, y_min),
        "width"     : width,
        "height"    : height,
    }

    if output_path is not None:
        rows = grid.tolist()
        lines = [
            "# Auto-generated by occupancy_grid.py",
            f"# resolution : {resolution} m/cell",
            f"# origin     : ({x_min:.6f}, {y_min:.6f})  # [m] グリッド左下の世界座標",
            f"# width      : {width}  # X 方向セル数",
            f"# height     : {height}  # Y 方向セル数",
            "",
            "RESOLUTION = " + repr(resolution),
            f"ORIGIN = ({x_min:.6f}, {y_min:.6f})",
            f"WIDTH  = {width}",
            f"HEIGHT = {height}",
            "",
            "# GRID[row][col]: 0 = 空き, 1 = 障害物",
            "GRID = [",
        ]
        for row in rows:
            lines.append("    " + repr(row) + ",")
        lines.append("]")
        lines.append("")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        print(f"[occupancy_grid] 保存: {output_path}")
        print(f"  グリッドサイズ : {width} x {height} cells")
        print(f"  解像度         : {resolution} m/cell")
        print(f"  原点 (左下)    : ({x_min:.4f}, {y_min:.4f}) m")
        print(f"  障害物セル数   : {int(grid.sum())}")

    return grid, info


def load_occupancy_grid(
    urdf_path: str | None = None,
    npy_path: str | None = None,
    resolution: float = 0.01,
) -> tuple[np.ndarray, dict]:
    """
    占有格子地図を 2 次元配列として返す。

    優先順位:
      1. npy_path が指定されていてファイルが存在する → .npy を読み込む
      2. urdf_path が指定されている              → URDF から生成する
      3. どちらも未指定                           → スクリプトと同じディレクトリの
                                                    field.urdf / occupancy_grid.npy を自動検索

    Parameters
    ----------
    urdf_path : str | None
        field.urdf のパス。
    npy_path : str | None
        保存済み occupancy_grid.npy のパス。
    resolution : float
        URDF から生成する場合の解像度 [m/cell]。

    Returns
    -------
    grid : np.ndarray, shape (H, W), dtype=uint8
        0 = 空き、1 = 障害物。
    info : dict
        {"resolution", "origin", "width", "height"}
        .npy から読み込んだ場合は origin=(0,0) のダミー値。
    """
    _dir = os.path.dirname(os.path.abspath(__file__))

    # 1. .py ファイルが使える場合
    _py = npy_path or os.path.join(_dir, "occupancy_grid_data.py")
    if os.path.exists(_py):
        import importlib.util
        spec = importlib.util.spec_from_file_location("occupancy_grid_data", _py)
        mod  = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        grid = np.array(mod.GRID, dtype=np.uint8)
        info: dict = {
            "resolution": mod.RESOLUTION,
            "origin"    : mod.ORIGIN,
            "width"     : mod.WIDTH,
            "height"    : mod.HEIGHT,
        }
        return grid, info

    # 2. URDF から生成
    _urdf = urdf_path or os.path.join(_dir, "field.urdf")
    return generate_occupancy_grid_from_urdf(
        urdf_path=_urdf,
        resolution=resolution,
        output_path=_py,
    )


# ── メインエントリポイント ────────────────────────────────────────────────────
if __name__ == "__main__":
    _dir      = os.path.dirname(os.path.abspath(__file__))
    _urdf     = os.path.join(_dir, "field.urdf")
    _out_py   = os.path.join(_dir, "occupancy_grid_data.py")

    _grid, _info = generate_occupancy_grid_from_urdf(
        urdf_path=_urdf,
        resolution=0.01,
        output_path=_out_py,
    )

    # ── 可視化 (matplotlib がある場合のみ) ──────────────────────────────────
    try:
        import matplotlib.pyplot as plt

        _origin = _info["origin"]
        _extent = [
            _origin[0],
            _origin[0] + _info["width"]  * _info["resolution"],
            _origin[1],
            _origin[1] + _info["height"] * _info["resolution"],
        ]

        fig, ax = plt.subplots(figsize=(8, 8))
        ax.imshow(_grid, origin="lower", cmap="gray_r", extent=_extent)
        ax.set_xlabel("X [m]")
        ax.set_ylabel("Y [m]")
        ax.set_title("Occupancy Grid (from field.urdf)")
        ax.set_aspect("equal")
        plt.tight_layout()

        _out_png = os.path.join(_dir, "occupancy_grid.png")
        plt.savefig(_out_png, dpi=150)
        print(f"[occupancy_grid] 画像保存: {_out_png}")
        plt.show()
    except ImportError:
        print("[occupancy_grid] matplotlib が見つからないため可視化をスキップします。")
